spring.application.name=servicioreservas

server.port=8082
spring.datasource.url=jdbc:mysql://localhost:3306/club_deportivo
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

clients.cancha.url=http://localhost:8081